### ISSUE TITLE
PhpMyadmin login not working

### ISSUE THREAD

**Issue by shilpaannalex** [shineklbm/guki#3]
I am getting an error 
`mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known`

**Comment by shineklbm** [comment]
Hello @shilpaannalex I think its probably because of the host name, can you please try `mysql` as the hostname? Please use `root` as both username and password (You may please change it in `docker-compose.yml` file)

**Comment by shilpaannalex** [comment]
ok thanks! Its working for me.

**Comment by shineklbm** [comment]
Ok perfect!
